### ISSUE TITLE
Feat: Deno support

### ISSUE THREAD

**Issue by c43721** [upstash/upstash-redis#23]
I'm an avid supporter of Deno, and I LOVE using upstash with Deno. It's very easy to do with the built in fetch function.

Support for deno runtime, either though a mod.ts file exporting the main methods or some interop script to remove the fetch import would both work. 

I would be willing to work on this if needed.

**Comment by chronark** [comment]
Hi @c43721 
100% agree: deno is great, unfortunately we had some issues with compatibility.
I had written the kafka client with deno at first (See [this commit](https://github.com/upstash/upstash-kafka/tree/83b3a00f39a19d7c54947c4ab0e458ed33a983ea). However we were not able to get it running on special platforms such as cloudflare workers because the shims created by `dnt` did not work.

Did you try https://esm.sh/@upstash/redis? It's an automated tool to make it deno compatible.
If that works I would just update the readme for now.

# Fetch dependency:
I'm not sure on the timelime when `fetch` will be no longer hidden behind an experimental flag in nodejs, but at that point we can also remove that dependency and it should be super easy, because we no longer have any prod dependencies.

Ideally we write it in deno and then convert and package to npm but we can also try a temporary workaround the other way.
I'm not exactly sure what is needed, I 
Can you create a pr with your suggestions and we'll work out any issues in cloudflare or other platforms from there?

**Comment by c43721** [comment]
Thanks for the info! I'll have to look into this another time, but I will certainly try to attempt a PR at this when I get some free time.

**Comment by chronark** [comment]
Just tried to use esm.sh but I'm getting lots of errors and I am not sure why. Looks like it's not as easy as I thought.

```
 deno run --allow-all ./main.ts
Download https://cdn.esm.sh/v67/@upstash/redis@v1.0.0-alpha.0/dist/index.d.ts
Check file:///Users/andreas/github/upstash/upstash-redis/examples/deno/main.ts
error: TS7030 [ERROR]: Not all code paths return a value.
function slowCases(enc: string): TextEncodings | undefined {
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/std@0.125.0/node/_utils.ts:87:34

TS6133 [ERROR]: 'isDeepEqual' is declared but its value is never read.
function isDeepEqual(val1: unknown, val2: unknown): boolean {
         ~~~~~~~~~~~
    at https://deno.land/std@0.125.0/node/internal/util/comparisons.ts:48:10

TS7029 [ERROR]: Fallthrough case in switch.
    case "string":
    ~~~~~~~~~~~~~~
    at https://deno.land/std@0.125.0/node/internal/util/comparisons.ts:501:5

TS6196 [ERROR]: 'GenericFunction' is declared but never used.
type GenericFunction = (...args: any[]) => any;
     ~~~~~~~~~~~~~~~
    at https://deno.land/std@0.125.0/node/internal/errors.ts:73:6

TS7030 [ERROR]: Not all code paths return a value.
function get<T>(obj: Record<string, T>, key: string): T | undefined {
                                                      ~~~~~~~~~~~~~
    at https://deno.land/std@0.125.0/flags/mod.ts:68:55

TS7030 [ERROR]: Not all code paths return a value.
  getOwnPropertyDescriptor: (_target, name) => {
                            ~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/std@0.125.0/node/_process/process.ts:43:29

TS7030 [ERROR]: Not all code paths return a value.
): string | undefined {
   ~~~~~~~~~~~~~~~~~~
    at https://deno.land/std@0.125.0/node/string_decoder.ts:100:4

TS7030 [ERROR]: Not all code paths return a value.
): string | undefined {
   ~~~~~~~~~~~~~~~~~~
    at https://deno.land/std@0.125.0/node/string_decoder.ts:125:4

TS7030 [ERROR]: Not all code paths return a value.
): string | undefined {
   ~~~~~~~~~~~~~~~~~~
    at https://deno.land/std@0.125.0/node/string_decoder.ts:143:4
```

**Comment by c43721** [comment]
Much thanks for your support in this! I'll be looking forward to using this soon!!!
