### ISSUE TITLE
Feat Telemetry error with wrangler

### ISSUE THREAD

**Issue by binou-31** [upstash/upstash-redis#268]
Hi,

After v1.6.1 with telemetry feature. It's impossible to run @upstash/redis with wrangler on Cloudflare Worker
Even if i set `UPSTASH_DISABLE_TELEMETRY` or not.

```
$ wrangler dev --local
[mf:err] /tmp/tmp-1158-u34FVafmubEJ/index.js:3967
      if (!process.env.UPSTASH_DISABLE_TELEMETRY) {
      ^

ReferenceError: process is not defined
    at new Redis2 (/opt/node_modules/@upstash/redis/esm/platforms/nodejs.js:25:9)
    at /opt/src/index.js:35:15
    at /tmp/tmp-1158-u34FVafmubEJ/index.js:4182:3
    at Script.runInContext (node:vm:141:12)
    at VMScriptRunner.runAsScript (/opt/node_modules/@miniflare/runner-vm/src/index.ts:25:12)
    at VMScriptRunner.run (/opt/node_modules/@miniflare/runner-vm/src/index.ts:84:12)
    at Miniflare.#reload (/opt/node_modules/@miniflare/core/src/index.ts:775:42)
    at Miniflare.getPlugins (/opt/node_modules/@miniflare/core/src/index.ts:1017:5)
    at createServer (/opt/node_modules/@miniflare/http-server/src/index.ts:369:19)
    at startServer (/opt/node_modules/@miniflare/http-server/src/index.ts:476:18)
```

issue is solved when i force v1.6.1 with `npm install @upstash/redis@v1.6.1`

**Comment by chronark** [comment]
Do you import from `@upstash/redis/cloudflare`?

**Comment by binou-31** [comment]
Everything works properly after changed the import statement like you said.

Thanks.
