### ISSUE TITLE
SvelteKit build on vercel fails - works locally

### ISSUE THREAD

**Issue by 3xHarry** [upstash/upstash-redis#279]
Building my project locally works fine and even starting the build with vite preview, however, once i push, vercel is not able to build with `'@upstash/redis' ` as a dependency. Removing `"@upstash/redis"` build successfully. 

this is the error log form vercel:

```
file:///vercel/path0/node_modules/@upstash/redis/esm/platforms/nodejs.js:14
--
13:12:47.831 | if (configOrRequester.url.startsWith(" ") \|\|
13:12:47.831 | ^
13:12:47.831 |  
13:12:47.832 | TypeError: Cannot read properties of undefined (reading 'startsWith')
13:12:47.832 | at new Redis (file:///vercel/path0/node_modules/@upstash/redis/esm/platforms/nodejs.js:14:35)
13:12:47.832 | at file:///vercel/path0/.svelte-kit/output/server/entries/pages/_layout.server.ts.js:539:15
13:12:47.832 | at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
13:12:47.832 | at async Promise.all (index 0)
13:12:47.832 | at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
13:12:47.832 | at async Promise.all (index 0)
13:12:47.832 | at async prerender (file:///vercel/path0/node_modules/@sveltejs/kit/src/core/prerender/prerender.js:381:18)
13:12:47.832 |  
13:12:47.832 | Node.js v18.12.1
13:12:47.836 | [vite-plugin-sveltekit-build] Prerendering failed with code 1
13:12:47.837 | error during build:
13:12:47.837 | Error: Prerendering failed with code 1
13:12:47.837 | at ChildProcess.<anonymous> (file:///vercel/path0/node_modules/@sveltejs/kit/src/exports/vite/index.js:483:15)
13:12:47.837 | at ChildProcess.emit (node:events:513:28)
13:12:47.837 | at ChildProcess._handle.onexit (node:internal/child_process:291:12)
13:12:47.919 | Error: Command "vite build" exited with 1
```

package.json
```
"devDependencies": {
		"@sveltejs/adapter-auto": "next",
		"@sveltejs/kit": "^1.0.0-next.581",
		"@types/gtag.js": "^0.0.12",
		"@types/lodash": "^4.14.182",
		"@typescript-eslint/eslint-plugin": "^5.10.1",
		"@typescript-eslint/parser": "^5.10.1",
		"autoprefixer": "^10.4.7",
		"esbuild": "^0.14.54",
		"eslint": "^8.12.0",
		"eslint-config-prettier": "^8.3.0",
		"eslint-plugin-svelte3": "^4.0.0",
		"postcss": "^8.4.14",
		"prettier": "^2.5.1",
		"prettier-plugin-svelte": "^2.5.0",
		"svelte": "^3.54.0",
		"svelte-check": "^2.10.2",
		"svelte-preprocess": "^4.10.7",
		"tailwindcss": "^3.0.24",
		"tslib": "^2.4.1",
		"typescript": "^4.9.4",
		"vite": "^4.0.0"
	},
	"type": "module",
	"dependencies": {
		"@balancer-labs/sdk": "^0.1.38",
		"@formkit/auto-animate": "^1.0.0-beta.1",
		"@metamask/contract-metadata": "^1.35.0",
		"@metamask/providers": "^8.1.1",
		"@popperjs/core": "^2.11.5",
		"@sveltejs/adapter-static": "^1.0.0-next.49",
		"@traderxyz/nft-swap-sdk": "^0.30.0",
		"@typechain/ethers-v5": "^10.1.1",
		"chart.js": "^3.8.0",
		"classnames": "^2.3.1",
		"currency.js": "^2.0.4",
		"dayjs": "^1.11.3",
		"ethereumjs-util": "^7.1.5",
		"ethers": "^5.7.2",
		"from-exponential": "^1.1.1",
		"graphql": "^16.6.0",
		"graphql-request": "^5.0.0",
		"lodash": "^4.17.21",
		"millify": "^4.0.0",
		"process": "^0.11.10",
		"rollup-plugin-polyfill-node": "^0.10.2",
		"svelte-local-storage-store": "^0.3.1",
		"svelte-seo": "^1.4.1",
		"typechain": "^8.1.0",
		"uninstall": "^0.0.0",
		"web3modal": "^1.9.8",
		"yup": "^0.32.11"
	}
```

**Comment by chronark** [comment]
```
13:12:47.832 | TypeError: Cannot read properties of undefined (reading 'startsWith')
```
indicates that you are passing undefined as url or token
can you double check how you initialize the redis client?

@3xHarry

**Comment by 3xHarry** [comment]
```javascript
const UPSTASH_REDIS_REST_URL = import.meta.env.VITE_UPSTASH_REDIS_REST_URL;
const UPSTASH_REDIS_REST_TOKEN = import.meta.env.VITE_UPSTASH_REDIS_REST_TOKEN;

const redis = new Redis({
	url: UPSTASH_REDIS_REST_URL,
	token: UPSTASH_REDIS_REST_TOKEN,
});
```
Ser you were right, I realized that i have to prefix the env variables with VITE_ on Vercel. The issue can be closed!

**Comment by chronark** [comment]
cool, glad it was an easy fix
