### ISSUE TITLE
Cloudflare example does not work

### ISSUE THREAD

**Issue by chronark** [upstash/upstash-redis#8]
Steps to reproduce:
1. `git clone git@github.com:upstash/upstash-redis.git`
2. `cd upstash-redis/examples/workers-with-upstash/`
3. Fill in account_id and secrets in `wrangler.toml`
4. `wrangler dev`
5. Visit `http://localhost:8787`

![image](https://user-images.githubusercontent.com/18246773/140583855-253862f5-0556-4bf7-9353-95357521fdb5.png)

There are unfortunately no logs visible in the dashboard.

Error:
```bash
wrangler dev

added 8 packages, and audited 9 packages in 652ms

found 0 vulnerabilities
👂  Listening on http://127.0.0.1:8787
🌀  Detected changes...
💁  Ignoring stale first change
[2021-11-05 23:01:52] GET workers-with-redis.chronark.workers.dev/ HTTP/1.1 500 Internal Server Error
TypeError: Illegal invocation
    at worker.js:1:6853
    at new Promise (<anonymous>)
    at r (worker.js:1:6828)
    at u (worker.js:1:7788)
    at p (worker.js:1:8303)
    at worker.js:1:5901
    at worker.js:1:5998 at line 0, col 6851
{
  "exceptionDetails": {
    "columnNumber": 6851,
    "exception": {
      "className": "TypeError",
      "description": "TypeError: Illegal invocation\n    at worker.js:1:6853\n    at new Promise (<anonymous>)\n    at r (worker.js:1:6828)\n    at u (worker.js:1:7788)\n    at p (worker.js:1:8303)\n    at worker.js:1:5901\n    at worker.js:1:5998",
      "preview": null,
      "subtype": "error",
      "type": "object",
      "value": null
    },
    "lineNumber": 0,
    "text": "Uncaught (in promise)",
    "url": "worker.js"
  },
  "timestamp": 1636149712692
}
TypeError: Illegal invocation at line 0, col -2
{
  "exceptionDetails": {
    "columnNumber": -2,
    "exception": {
      "className": "TypeError",
      "description": "TypeError: Illegal invocation",
      "preview": null,
      "subtype": "error",
      "type": "object",
      "value": null
    },
    "lineNumber": 0,
    "text": "Uncaught (in response)",
    "url": "undefined"
  },
  "timestamp": 1636149712692
}
```

**Comment by ademilter** [comment]
Thank you for the feedback. please use version [v0.1.22](https://github.com/upstash/upstash-redis/releases/tag/v0.1.22)
